name: Reusable deploy
on: 
 workflow_call:
    inputs:
      artifact-name:
        description: the name of the deployable artifact bfiles
        required: false
        default: dist
        type: string
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with: 
          name: ${{ inputs.artifact-name }}
      - name: Output informations
        run: echo "Deploying & uploading"